global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'card-service'
    static_configs:
      - targets: ['card-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'matchmaking-service'
    static_configs:
      - targets: ['matchmaking-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'game-battle-service'
    static_configs:
      - targets: ['game-battle-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'game-result-service'
    static_configs:
      - targets: ['game-result-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s